
export const SIGNUP_ACTION = 'SIGNUP_ACTION'

export const SIGNIN_ACTION = 'SIGNIN_ACTION'

export const SIGNEDIN_ACTION = 'SIGNEDIN_ACTION'

export const LOGOUT_ACTION = 'LOGOUT_ACTION'

export const LOGOUTED_ACTION = 'LOGOUTED_ACTION'

export const GOOGLESIGNIN_ACTION = 'GOOGLESIGNIN_ACTION'

export const FORGET_PASSWORD = 'FORGET_PASSWORD'

export const SET_ALERT = 'SET_ALERT'

export const RESET_ALERT = 'RESET_ALERT'
